### ISSUE TITLE
Altium schematics reference non-embedded image

### ISSUE THREAD

**Issue by cibomahto** [betrusted-io/betrusted-hardware#2]
Thanks for providing these as open hardware designs!

The '00_map.SchDoc' files in both the truste_io_evt2 and trusted_io_dvt1 projects are missing embedded images:
![image](https://user-images.githubusercontent.com/44493/100074353-e92fb500-2e3e-11eb-891b-44f00d58da86.png)

**Comment by bunnie** [comment]
Good call! thanks for pointing that out. I clicked the "embed" button on the UI and hopefully that saved the image into the .SchDoc file with commit https://github.com/betrusted-io/betrusted-hardware/commit/6c061859211b1b64149b644710691fd966f53876.

If this fixes it for you, please close the issue!
