### ISSUE TITLE
Question: Disabling Wifi

### ISSUE THREAD

**Issue by xloem** [betrusted-io/betrusted-hardware#3]
It is such a breath of fresh air to see how security conscious your work is.

I couldn't see what the plans were for providing non-networked use of a device.  Is there a way to physically cut power to, and/or remove, the wifi chip?

**Comment by bunnie** [comment]
The wifi chip is firewalled via an FPGA that is in the "untrusted" domain, but the FPGA is still open source and you control its function. To that end, there are many simple ways to permanently defeat the wifi chip. The easiest is to just hold its RESET line asserted. Another option would be to remove or damage the clock chip that provides its timebase; or you could remove or damage the ferrite beads that supply power to the analog/RF section, if for some reason you have suspicion that the chip could somehow still run RESET asserted and the clock stopped.

**Comment by xloem** [comment]
Thank you for the detailed reply.

If you ever redesign, add my vote in for hardware switches/blowable fuses to cut power to radios, sensors, actuators, or general modularity =)
